### ISSUE TITLE
[Starbook MK VI - AMD] Touchpad stopped working and does not show up via libinput

### ISSUE THREAD

**Issue by 3lpsy** [StarLabsLtd/touchpad#2]
I can't seem to reenable my trackpad. I have tried pushing F10 and rebooting. FN + F10 and rebooting. Trying this in different kernels. Booting into a manjaro live USB and trying to reenabel via F10.

When I run libinput list-devices, no "Touchpad" shows up. Same with xinput list.

Can you please provide guidance on debugging this issues? Is it possible it was disable via BIOS? I checked the BIOS (AMI) and there doesn't seem to be an option for it.

**Comment by amcewen** [comment]
Thanks for the pointer @3lpsy!  The touchpad has been "broken" on my laptop for the past week or two, and TIL that there's a "disable touchpad" on `Fn`+`F10`!  I have no idea how I managed to turn it off, but have got it back on now.  Thanks!
